### ISSUE TITLE
启动运行pgo_launch.py一会就出现 [lio_node-1] NO Effective Points!

### ISSUE THREAD

**Issue by chj0728** [liangheming/FASTLIO2_ROS2#23]
你好请问在室内小场景下，启动了pgo_launch.py，静止了一会就会出现如下现象应该怎么解决：

---
![Image](https://github.com/user-attachments/assets/0169f7ee-0372-48ac-9e94-00c775d58f0f)
---
![Image](https://github.com/user-attachments/assets/4779ac5f-59e4-479d-aab4-13fafa2a87a5)
---

`pgo.yaml`  和 `lio.yaml` 的 配置文件如下：
```yaml
cloud_topic: /fastlio2/body_cloud
odom_topic: /fastlio2/lio_odom
map_frame: map
local_frame: lidar

key_pose_delta_deg: 10
key_pose_delta_trans: 0.5
loop_search_radius: 1.0
loop_time_tresh: 60.0
loop_score_tresh: 0.15
loop_submap_half_range: 5
submap_resolution: 0.1
min_loop_detect_duration: 5.0
```
```yaml
imu_topic: /livox/imu
lidar_topic: /livox/lidar
body_frame: body
world_frame: lidar
print_time_cost: false

lidar_filter_num: 6
lidar_min_range: 0.10 #0.5
lidar_max_range: 10   #30.0
scan_resolution: 0.05 #0.15
map_resolution: 0.10 #0.3

cube_len: 300
det_range: 60
move_thresh: 1.5 #1.5

na: 0.01
ng: 0.01
nba: 0.0001
nbg: 0.0001

imu_init_num: 20
near_search_num: 5 #5
ieskf_max_iter: 5

gravity_align: true
esti_il: false

r_il: [1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0]
t_il: [-0.011, -0.02329, 0.04412]

lidar_cov_inv: 1000.0
```
